### ISSUE TITLE
bug: WorkStatus not created for Namespace and Service

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/ocm-status-addon#79]
### Describe the bug

The status add-on agent does not create a WorkStatus object if the corresponding workload object is a Namespace or a Service. This makes no sense to me. These kinds of object have status and it could be used in the so-called "combined status" feature, and possibly additional future features, of KubeStellar.

### Steps To Reproduce

Use `test/e2e/run-test.sh` to run a simple scenario. Look at the Binding in wds1, see that it includes a reference to a Namespace. Look for WorkStatus objects in its1, see that they are there for the Deployment object but not the Namespace object.

### Expected Behavior

I expected to get a WorkStatus for every pair of (workload object, WEC that said object goes to) --- at least for workload objects that have `.status`.

### Additional Context

These three are explicitly excluded by https://github.com/kubestellar/ocm-status-addon/blob/v0.2.0-rc10/pkg/agent/agent.go#L39-L41, under the irrelevant comment "generally all resources not creating a status should be excluded".

https://github.com/kubestellar/kubestellar/issues/2413

https://github.com/kubestellar/kubestellar/issues/1851

**Comment by pdettori** [comment]
@MikeSpreitzer yes, this was intentional (as in https://github.com/kubestellar/ocm-status-addon/blob/5e3d1080ae5c3e19040bce22e4b4581697776116/pkg/agent/agent.go#L31-L42)  as I did not initially consider a use case for namespace and service status. But since now we do have a use case for combined status (and other future features) I agree that we should re-enable them.
